routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Auth::routes();

Route::get('/', 'HomeController@index');
Route::get('/home', 'HomeController@index');
Route::get('/meal-order/{meal_id}', 'OrderController@publicOrder');

Route::group(['middleware' => 'checkRole:admin'], function () {    
    Route::resource('user', 'UserController');
    Route::get('user/{user_id}/edit', 'UserController@edit')->name('user.edit');
    Route::post('meal/status', 'MealController@status')->name('meal.status');
    Route::resource('meal', 'MealController');
    Route::get('meal/{meal_id}/edit', 'MealController@edit')->name('meal.edit');
    Route::get('/order/{meal_id}', ['as' => 'order', 'uses' => 'OrderController@index'] );
    Route::post('status', 'OrderController@status' )->name('order.status');
});

Route::group(['middleware' => 'checkRole:user'], function () {
  Route::get('/shop/{meal_id}', ['as' => 'shop', 'uses' => 'ShopController@create'] );
  Route::get('order', 'OrderController@myOrder' )->name('order.index');
  Route::get('order/{order_id}/edit', 'OrderController@edit' )->name('order.edit');
  Route::post('order/{order_id}', 'OrderController@update' )->name('order.update');
  Route::resource('shop', 'ShopController');
});

resources/views/header.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <!-- CSRF Token -->
        <meta name="csrf-token" content="{{ csrf_token() }}">

        <title>{{ config('app.name', 'Laravel') }}</title>

        <!-- Scripts -->
        
        <script src="{{ asset('public/js/jquery.js') }}"></script>
        <script src="{{ asset('public/js/app.js') }}" defer></script>
        <script src="{{ asset('public/js/bootstrap-select.min.js') }}"></script>
        <script src="{{ asset('public/js/switchery.min.js') }}"></script>
        <script src="{{ asset('public/js/bootstrap-datepicker.js') }}"></script>

        
        
        <!-- Fonts -->
        <link rel="dns-prefetch" href="//fonts.gstatic.com">
        <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

        <!-- Styles -->
        <link href="{{ asset('public/css/app.css') }}" rel="stylesheet">
        <link href="{{ asset('public/css/bootstrap-datepicker.css') }}" rel="stylesheet">
        <link href="{{ asset('public/css/switchery.min.css') }}" rel="stylesheet">
        <link href="{{ asset('public/css/bootstrap-select.min.css') }}" rel="stylesheet">
       
        <title>Laravel</title>

        <!-- Fonts -->
        <link href="https://fonts.googleapis.com/css?family=Nunito:200,600" rel="stylesheet">

        <!-- Styles -->
        <style>
            html, body {
                background-color: #fff;
                color: #636b6f;
                font-family: 'Nunito', sans-serif;
                font-weight: 200;
                height: 100vh;
                margin: 0;
            }

            .full-height {
                height: 100vh;
            }

            .flex-center {
                align-items: center;
                display: flex;
                justify-content: center;
            }

            .position-ref {
                position: relative;
            }

            .top-right {
                position: absolute;
                right: 10px;
                top: 18px;
            }

            .content {
                text-align: center;
            }

            .title {
                font-size: 84px;
            }

            .links > a {
                color: #636b6f;
                padding: 0 25px;
                font-size: 13px;
                font-weight: 600;
                letter-spacing: .1rem;
                text-decoration: none;
                text-transform: uppercase;
            }

            .m-b-md {
                margin-bottom: 30px;
            }

            table{
                min-width: 400px;
            }

            table tr.open {
                background-color: #4eff4754 !important;
            }
            table tr.not-open {
                background-color: #ef132754 !important;
            }

            .dropdown-menu.show .dropdown-menu.inner{
                display: block;
            } 

            .glyphicon-ok:before {                
                content: url("{{ asset('public/check.svg') }}");
            }

            .bootstrap-select .dropdown-toggle:focus{
                outline: none !important;
            }

            .form-control.dropdown.bootstrap-select {
                border: 1px solid #00000057;
            }
        </style>
    </head>
    <body>
        <div >
            <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
                <div class="container">
                    <a class="navbar-brand" href="{{ url('/') }}">
                        {{ config('app.name', 'Subway') }}
                    </a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                        <span class="navbar-toggler-icon"></span>
                    </button>

                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <!-- Left Side Of Navbar -->
                        <ul class="navbar-nav mr-auto">

                        </ul>

                        <!-- Right Side Of Navbar -->
                        <ul class="navbar-nav ml-auto">
                            <!-- Authentication Links -->
                            @guest
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                                </li>
                                @if (Route::has('register'))
                                    <li class="nav-item">
                                        <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                    </li>
                                @endif
                            @else
                            
                                @include('menu')
                                
                                <li class="nav-item dropdown">
                                    <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                        {{ Auth::user()->name }}
                                    </a>

                                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                        <a class="dropdown-item" href="{{ route('logout') }}"
                                        onclick="event.preventDefault();
                                                        document.getElementById('logout-form').submit();">
                                            {{ __('Logout') }}
                                        </a>

                                        <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                            @csrf
                                        </form>
                                    </div>
                                </li>
                            @endguest
                        </ul>
                    </div>
                </div>
            </nav>

            <main class="py-4 pl-5 pr-5 pt-2">
                @yield('content')
            </main>
        </div>
    </body>
</html>

resources/views/home.blade.php
@extends('header')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        @if (Auth::user())
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">{{ __('Dashboard') }}</div>
                    <div class="card-body">
                        @if (session('status'))
                            <div class="alert alert-success" role="alert">
                                {{ session('status') }}
                            </div>
                        @endif

                        Welcome {{ Auth::user()->name }} !
                    </div>
                </div>
            </div>
        @endif
    </div>
</div>
@endsection

resources/views/menu.blade.php
@if (Auth::user()->role == 'admin')
    <li class="nav-item">
        <a class="nav-link" href="{{ route('user.index') }}">{{ __('Users') }}</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{{ route('meal.index') }}">{{ __('Meal') }}</a>
    </li>
@else
    <li class="nav-item">
        <a class="nav-link" href="{{ route('shop.index') }}">{{ __('Shop Meal') }}</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{{ route('order.index') }}">{{ __('My Order') }}</a>
    </li>
@endif