routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Auth::routes();

Route::get('/', 'HomeController@index');
Route::get('/home', 'HomeController@index');
Route::get('/meal-order/{meal_id}', 'OrderController@publicOrder');

Route::group(['middleware' => 'checkRole:admin'], function () {    
    Route::resource('user', 'UserController');
    Route::get('user/{user_id}/edit', 'UserController@edit')->name('user.edit');
    Route::post('meal/status', 'MealController@status')->name('meal.status');
    Route::resource('meal', 'MealController');
    Route::get('meal/{meal_id}/edit', 'MealController@edit')->name('meal.edit');
    Route::get('/order/{meal_id}', ['as' => 'order', 'uses' => 'OrderController@index'] );
    Route::post('status', 'OrderController@status' )->name('order.status');
});

Route::group(['middleware' => 'checkRole:user'], function () {
  Route::get('/shop/{meal_id}', ['as' => 'shop', 'uses' => 'ShopController@create'] );
  Route::get('order', 'OrderController@myOrder' )->name('order.index');
  Route::get('order/{order_id}/edit', 'OrderController@edit' )->name('order.edit');
  Route::post('order/{order_id}', 'OrderController@update' )->name('order.update');
  Route::resource('shop', 'ShopController');
});

app/Meal.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use GoldSpecDigital\LaravelEloquentUUID\Database\Eloquent\Uuid;

class Meal extends Model
{
    use Uuid;
    protected $keyType = 'string';
    public $incrementing = false;
    protected $guarded = [];

    protected $table = 'meal'; 

    protected $fillable = [
        'meal_title', 'meal_date', 'is_open',
    ];
}

app/Http/Controllers/MealController.php
<?php

namespace App\Http\Controllers;

//use Request;
use Illuminate\Http\Request;
use Response;
use App\Meal;

class MealController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $meal = Meal::all()->toArray();
        return view('meal.index', compact('meal'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('meal.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'meal_title'    =>  'required'
        ]);
        
        if(($request->get('is_open') == 'on')){
            Meal::where('is_open', "1")->update(array('is_open' => "0"));
        }

        $meal = new Meal([
            'meal_title'    =>  $request->get('meal_title'),
            'meal_date'     =>  $request->get('meal_date'),
            'is_open'     =>  ($request->get('is_open') == 'on') ? "1" : "0"
        ]);

        $meal->save();
        return redirect()->route('meal.index')->with('success', 'Meal Data Added');
    }

    public function status(Request $request)
    {
    
        $mealID = $request->get('mealId');
        $mealStatus = $request->get('status');

        Meal::where('is_open', "1")->update(array('is_open' => "0"));

        Meal::where('id', $mealID)->update(array('is_open' => $mealStatus));

        return response()->json(['result'=>'success']);

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $meal = Meal::find($id);
        return view('meal.edit', compact('meal'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $meal_id)
    {
        $this->validate($request, [
            'meal_title'    =>  'required'
        ]);
        
        if(($request->get('is_open') == 'on')){
            Meal::where('is_open', "1")->update(array('is_open' => "0"));
        }

        Meal::where('id',$meal_id)
        ->update([
            'meal_title'    =>  $request->get('meal_title'),
            'meal_date'     =>  $request->get('meal_date'),
            'is_open'     =>  ($request->get('is_open') == 'on') ? "1" : "0"
        ]);
       
        return redirect()->route('meal.index')->with('success', 'Meal Data Updated.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/meal/create.blade.php
@extends('header')



@section('content')
<div class="row">
 <div class="col-md-12">
  <br />
  <h3 aling="center">Add Meal</h3>
  <br />
  @if(count($errors) > 0)
  <div class="alert alert-danger">
   <ul>
   @foreach($errors->all() as $error)
    <li>{{$error}}</li>
   @endforeach
   </ul>
  </div>
  @endif
  @if(\Session::has('success'))
  <div class="alert alert-success">
   <p>{{ \Session::get('success') }}</p>
  </div>
  @endif

  <form method="post" action="{{url('meal')}}" autocomplete="off">
   {{csrf_field()}}
   <div class="form-group">
    <input type="text" name="meal_title" class="form-control" placeholder="Enter Meal" />
   </div>
   <div class="form-group">
    <input type="text" name="meal_date" class="date form-control" placeholder="Enter Date" />
   </div>
   <div class="form-group">
    <input type="checkbox"  name="is_open" class="js-switch" >
    </div>
   <div class="form-group">
    <input type="submit" class="btn btn-primary" />
   </div>
  </form>
 </div>
</div>
<script type="text/javascript">
    jQuery('.date').datepicker({  
       format: 'yyyy-mm-dd',
       autoclose: true,
       orientation: "auto",
     });  

     let elems = Array.prototype.slice.call(document.querySelectorAll('.js-switch'));

    elems.forEach(function(html) {
        let switchery = new Switchery(html,  { size: 'small' });
    });
</script> 
@endsection

resources/views/meal/edit.blade.php
@extends('header')

@section('content')
<div class="row">
 <div class="col-md-12">
  <br />
  <h3 aling="center">Edit Meal</h3>
  <br />
  @if(count($errors) > 0)
  <div class="alert alert-danger">
   <ul>
   @foreach($errors->all() as $error)
    <li>{{$error}}</li>
   @endforeach
   </ul>
  </div>
  @endif


  <form method="post" action="{{route('meal.update',$meal->id)}}" autocomplete="off">
   {{csrf_field()}}
   {{ method_field('PUT') }}
   <div class="form-group">
    <input type="text" name="meal_title" class="form-control" placeholder="Enter Meal" value="{{$meal->meal_title}}" />
   </div>
   <div class="form-group">
    <input type="text" name="meal_date" class="date form-control" placeholder="Enter Date" value="{{date('Y-m-d',strtotime($meal->meal_date))}}" />
   </div>
   <div class="form-group">
    <input type="checkbox"  name="is_open" class="js-switch" {{($meal->is_open) ? 'checked' : ''}} >
    </div>
   <div class="form-group">
    <input type="submit" class="btn btn-primary" />
   </div>
  </form>
 </div>
</div>
<script type="text/javascript">
    jQuery('.date').datepicker({  
       format: 'yyyy-mm-dd',
       autoclose: true,
       orientation: "auto",
     });  

     let elems = Array.prototype.slice.call(document.querySelectorAll('.js-switch'));

    elems.forEach(function(html) {
        let switchery = new Switchery(html,  { size: 'small' });
    });
</script> 
@endsection

resources/views/meal/index.blade.php
@extends('header')

@section('content')

<div class="row">
 <div class="col-md-12">
  <br />
  <h3>Meal Details</h3>
  <br />
  @if($message = Session::get('success'))
  <div class="alert alert-success">
   <p>{{$message}}</p>
  </div>
  @endif
  <div align="right">
   <a href="{{route('meal.create')}}" class="btn btn-primary">Add</a>
   <br />
   <br />
  </div>
  <table class="table table-bordered table-striped">
   <tr>
    <th>Meal</th>
    <th>Is Open</th>
    <th>Date</th>
    <th></th>
    <th>View Orders</th>
   </tr>
   @foreach($meal as $row)
   <tr>
    <td>{{$row['meal_title']}}</td>
    <td><input type="checkbox" data-id="{{ $row['id'] }}" name="status" class="js-switch" {{ $row['is_open'] == 1 ? 'checked' : '' }}></td>
    <td>{{ date('d-m-Y', strtotime($row['meal_date']))}}</td>
    <td><a href="{{route('meal.edit', ['meal_id' => $row['id']])}}">Edit</a></td>
    <td><a href="{{route('order', ['meal_id' => $row['id']])}}">View</a></td>
   </tr>
   @endforeach
  </table>
 </div>
</div>
<script type="text/javascript">
    let elems = Array.prototype.slice.call(document.querySelectorAll('.js-switch'));

    elems.forEach(function(html) {
        let switchery = new Switchery(html,  { size: 'small' });
    });

    $(document).ready(function(){
    $('.js-switch').change(function () {
        /* $('.js-switch').prop('checked',false).removeAttr('checked');
         */

       /*  $('.js-switch').attr('checked', false).trigger("click");
        if ($(this).prop('checked') === true){
            console.log("Ad");
          //  $(this).attr('checked', true).trigger("click");
        } */
         

        let status = $(this).prop('checked') === true ? 1 : 0;
        let mealId = $(this).data('id');
        $.ajax({
            type: "POST",
            dataType: "json",
            url: '{{ route('meal.status') }}',
            data: {"_token": "{{ csrf_token() }}", 'status': status, 'mealId': mealId},
            success: function (data) {
                location.reload();
                console.log(data.message);
            }
        });
    });
});
</script> 
@endsection