routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Auth::routes();

Route::get('/', 'HomeController@index');
Route::get('/home', 'HomeController@index');
Route::get('/meal-order/{meal_id}', 'OrderController@publicOrder');

Route::group(['middleware' => 'checkRole:admin'], function () {    
    Route::resource('user', 'UserController');
    Route::get('user/{user_id}/edit', 'UserController@edit')->name('user.edit');
    Route::post('meal/status', 'MealController@status')->name('meal.status');
    Route::resource('meal', 'MealController');
    Route::get('meal/{meal_id}/edit', 'MealController@edit')->name('meal.edit');
    Route::get('/order/{meal_id}', ['as' => 'order', 'uses' => 'OrderController@index'] );
    Route::post('status', 'OrderController@status' )->name('order.status');
});

Route::group(['middleware' => 'checkRole:user'], function () {
  Route::get('/shop/{meal_id}', ['as' => 'shop', 'uses' => 'ShopController@create'] );
  Route::get('order', 'OrderController@myOrder' )->name('order.index');
  Route::get('order/{order_id}/edit', 'OrderController@edit' )->name('order.edit');
  Route::post('order/{order_id}', 'OrderController@update' )->name('order.update');
  Route::resource('shop', 'ShopController');
});

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\User;
use Carbon\Carbon;

class UserController extends Controller
{
    public function index()
    {
        $users = User::all();
        return view('user.index', compact('users'));
    }

    public function create()
    {
        return view('user.create');
    }

    public function store(Request $request)
    {
        $this->validate($request, [
            'name'    =>  'required',
            'email'    =>  'required|unique:users,email',
            'password' => 'required| min:4|confirmed',
            'password_confirmation' => 'required| min:4'
        ]);

        User::insert([
            'name'     =>  $request->get('name'),
            'email'     =>  $request->get('email'),
            'role'     =>  (!empty($request->get('role'))) ? $request->get('role') : "user",
            'password'     =>  bcrypt($request->get('password')),
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
        ]);
       
        return redirect()->route('user.index')->with('success', 'User successfully added.');

    }

    public function edit($user_id){
        $user = User::find($user_id);
        return view('user.edit', compact('user'));
    }

    public function update(Request $request,$user_id){
        $this->validate($request, [
            'name'    =>  'required',
            'email'    =>  'required|unique:users,email,'.$user_id,
            'password' => 'required| min:4|confirmed',
            'password_confirmation' => 'required| min:4'
        ]);

        User::where('id', $user_id)
        ->update([
            'name'     =>  $request->get('name'),
            'email'     =>  $request->get('email'),
            'role'     =>  (!empty($request->get('role'))) ? $request->get('role') : "user",
            'password'     =>  bcrypt($request->get('password'))
        ]);
       
        return redirect()->route('user.index')->with('success', 'User successfully Updated.');
        
    }


}

resources/views/user/create.blade.php
@extends('header')

@section('content')

<div class="row">
 <div class="col-md-12">
  <br />
  <h3 aling="center">Add User</h3>
  <br />
  @if(count($errors) > 0)
  <div class="alert alert-danger">
   <ul>
   @foreach($errors->all() as $error)
    <li>{{$error}}</li>
   @endforeach
   </ul>
  </div>
  @endif
  @if(\Session::has('success'))
  <div class="alert alert-success">
   <p>{{ \Session::get('success') }}</p>
  </div>
  @endif

  <form method="post" action="{{url('user')}}">
   {{csrf_field()}}

    <div class="form-group">
        <label for="name">Name</label>
        <input type="text" name="name" id="name" class="form-control" placeholder="Enter Name" value="{{old('name')}}" />
    </div>
   
    <div class="form-group">
        <label for="email">Email Address</label>
        <input type="email" name="email" id="email" class="form-control" placeholder="Enter Email" value="{{old('email')}}" />
    </div>

    <div class="form-group">
        <label for="password">Password</label>
        <input type="password" name="password" id="password" class="form-control" placeholder="*****" />
    </div>

    <div class="form-group">
        <label for="password_confirmation">Confirm Password</label>
        <input type="password" name="password_confirmation" id="password_confirmation" class="form-control" placeholder="*****" />
    </div>

   <div class="form-group">
    <label for="role">Role</label>
    <select name="role" id="role" class="form-control">
        <option value="">Select Role</option>
        <option value="admin">Admin</option>
        <option value="user">User</option>
    </select>
   </div>

   <div class="form-group">
    <input type="submit" class="btn btn-primary" />
   </div>
  </form>
 </div>
</div>

@endsection

resources/views/user/edit.blade.php
@extends('header')

@section('content')

<div class="row">
 <div class="col-md-12">
  <br />
  <h3 aling="center">Edit User</h3>
  <br />
  @if(count($errors) > 0)
  <div class="alert alert-danger">
   <ul>
   @foreach($errors->all() as $error)
    <li>{{$error}}</li>
   @endforeach
   </ul>
  </div>
  @endif
  @if(\Session::has('success'))
  <div class="alert alert-success">
   <p>{{ \Session::get('success') }}</p>
  </div>
  @endif

  <form method="post" action="{{route('user.update',$user->id)}}">
   {{csrf_field()}}
   {{ method_field('PUT') }}

    <div class="form-group">
        <label for="name">Name</label>
        <input type="text" name="name" id="name" class="form-control" placeholder="Enter Name" value="{{(old('name')) ? old('name') : $user->name}}" />
    </div>
   
    <div class="form-group">
        <label for="email">Email Address</label>
        <input type="email" name="email" id="email" class="form-control" placeholder="Enter Email" value="{{(old('email')) ? old('email') : $user->email}}" />
    </div>
    
    <div class="form-group">
        <label for="password">Password</label>
        <input type="password" name="password" id="password" class="form-control" placeholder="*****" />
    </div>

    <div class="form-group">
        <label for="password_confirmation">Confirm Password</label>
        <input type="password" name="password_confirmation" id="password_confirmation" class="form-control" placeholder="*****" />
    </div>

   <div class="form-group">
    <label for="role">Role</label>
    <select name="role" id="role" class="form-control">
        <option value="">Select Role</option>
        <option value="admin" {{($user->role == 'admin') ? 'selected' : ''}} >Admin</option>
        <option value="user" {{($user->role == 'user') ? 'selected' : ''}}>User</option>
    </select>
   </div>

   <div class="form-group">
    <input type="submit" class="btn btn-primary" />
   </div>
  </form>
 </div>
</div>

@endsection

resources/views/user/index.blade.php
@extends('header')

@section('content')

<div class="row">
 <div class="col-md-12">
 <br />
  <h3>User Details</h3>
  <br />
  @if(\Session::has('success'))
  <div class="alert alert-success">
   <p>{{ \Session::get('success') }}</p>
  </div>
  @endif
  <div align="right" class="pb-2">
   <a href="{{route('user.create')}}" class="btn btn-primary">Add User</a>
  </div>
  <table class="table table-bordered table-striped">
   <tr>
    <th>User Name</th>
    <th>Email Address</th>
    <th>Role</th>
    <th></th>
   </tr>
   @foreach($users as $row)
     <tr>    
        <td>{{$row->name}}</td>
        <td>{{$row->email}}</td>
        <td>{{ucfirst($row->role)}}</td>
        <td><a href="{{route('user.edit', ['user_id' => $row->id])}}">Edit</a></td>
     </tr>
   @endforeach
  </table>
 </div>
</div>

@endsection